name: gen art on push
run-name: ${{ github.actor }} waits for art
on: [push]
jobs:
  Gen_art:

    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Art generation was automatically triggered by an art ${{ github.event_name }} event."
      - run: echo "ğŸ§ Art is now generated on a ${{ runner.os }} server hosted by GitHub!"     	  
      - run: echo "ğŸ This job's status is ${{ job.status }}."
